"""T503 (metrics-dictionary §5.2): bridge_trade PnL decomposition.

Reference values for the "reduce existing position" case were generated by
running a real match_order scenario (agent m: open long 1000 @9990, book
mark moved by unrelated trades, then m sells 500 @10050) and reading the
actual TRADE_POSTING emitted by market_game_sim.ledger.account.apply_fill,
so the fixture mirrors production data rather than hand-derived numbers.
"""

from __future__ import annotations

from market_game_sim.metrics.bridge import bridge_trade


def test_bridge_trade_opening_position_with_fee_zero_residual():
    """pos_before=0, taker fee, price != mark -> residual must be exactly 0."""
    posting = {
        "wallet_delta_units": -999000,
        "position_delta_units": 1000,
        "entry_notional_delta_units": 9990000000,
        "fee_delta_units": 999000,
        "position_after_units": 1000,
    }
    result = bridge_trade(
        posting,
        vm_before_half=19980,
        vm_after_half=19980,
        trade_price_ticks=9990,
        position_before_units=0,
        mult=1000,
    )
    assert result["residual"] == 0
    assert result["fees"] == 999000


def test_bridge_trade_reduces_existing_position_with_moved_mark_zero_residual():
    """pos_before=1000 (existing long), mark moved since the position was
    opened (vb=20200, va=20100 half-ticks) -> revaluation term is nonzero
    and must be included in equity_delta for the residual to stay 0.  This
    is the scenario that reproduces the MULT/entry_notional precision gap
    (docs/reviews round 9): the previous implementation, which used
    equity_delta = wallet_delta_units alone, left a residual of 80,000,000
    here.
    """
    posting = {
        "wallet_delta_units": 24975000,
        "position_delta_units": -500,
        "entry_notional_delta_units": -4995000000,
        "fee_delta_units": 5025000,
        "position_after_units": 500,
    }
    result = bridge_trade(
        posting,
        vm_before_half=20200,
        vm_after_half=20100,
        trade_price_ticks=10050,
        position_before_units=1000,
        mult=1000,
    )
    assert result["residual"] == 0
    assert result["revaluation"] == -50000000


def test_bridge_trade_inconsistent_entry_notional_gives_nonzero_residual():
    """Negative case: if entry_notional_delta_units does not match the
    trade (e.g. a ledger bug corrupts it), the residual must surface as
    nonzero -- otherwise the check is not actually verifying anything.
    Same posting as the reduce-position case above but with a corrupted
    entry_notional_delta_units (off by 1 cash_unit).
    """
    posting = {
        "wallet_delta_units": 24975000,
        "position_delta_units": -500,
        "entry_notional_delta_units": -4995000001,
        "fee_delta_units": 5025000,
        "position_after_units": 500,
    }
    result = bridge_trade(
        posting,
        vm_before_half=20200,
        vm_after_half=20100,
        trade_price_ticks=10050,
        position_before_units=1000,
        mult=1000,
    )
    assert result["residual"] != 0
